### ISSUE TITLE
Post build command

### ISSUE THREAD

**Issue by CESMOtacon** [EnzoMeertens/KerbalKrashSystem#1]
Would you be able to include the command that is supposed to run post build to generate the DB?

**Comment by EnzoMeertens** [comment]
Hello,
Added to Source/KerbalKrashSystem/bin/Debug.

Kind regards,
Enzo Meertens
Date: Wed, 6 Jan 2016 12:04:42 -0800

**Comment by CESMOtacon** [comment]
Thank you!
