### ISSUE TITLE
ModuleManager 3.0.1 error in 4 cfg files

### ISSUE THREAD

**Issue by EnterTheNameHere** [EnzoMeertens/KerbalKrashSystem#11]
ModuleManager 3 indicates error in those files:
GameData/KerbalKrashSystem/Configs/KerbalKrashSystem_Other.cfg
GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_Leak/Configs/KerbalKrashSystem_Fuel_Leak.cfg
GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_Repair/Configs/KerbalKrashSystem_Repair.cfg
GameData/KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_Science/Configs/KerbalKrashSystem_Science.cfg

Error messages:
`[ERR 22:45:15.324] [ModuleManager] Error - more than one pass specifier on a node: KerbalKrashSystem/Configs/KerbalKrashSystem_Other/@PART[*]:HAS[!MODULE[ModuleKerbalKrashSystem_Exclude],!MODULE[ModuleKerbalKrash*],!MODULE[ModuleWheel],~PhysicsSignificance[1]]:AFTER[KerbalKrashSystem]:FOR[KerbalKrashSystem_Other]`

`[ERR 22:45:15.325] [ModuleManager] Error - more than one pass specifier on a node: KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_Leak/Configs/KerbalKrashSystem_Fuel_Leak/@PART[*]:HAS[@MODULE[ModuleKerbalKrashSystem_Container]]:AFTER[KerbalKrashSystem]:FOR[KerbalKrashSystem_Leak]`

`[ERR 22:45:15.326] [ModuleManager] Error - more than one pass specifier on a node: KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_Repair/Configs/KerbalKrashSystem_Repair/@PART[*]:HAS[@MODULE[ModuleKerbalKrash*]]:AFTER[KerbalKrashSystem]:FOR[KerbalKrashSystem_Repair]`

`[ERR 22:45:15.327] [ModuleManager] Error - more than one pass specifier on a node: KerbalKrashSystem/Plugins/KKS-mods/KerbalKrashSystem_Science/Configs/KerbalKrashSystem_Science/@PART[*]:HAS[@MODULE[ModuleScienceExperiment],!MODULE[ModuleKerbalKrashSystem*]]:AFTER[KerbalKrashSystem]:FOR[KerbalKrashSystem]`

(see line 16923 in log - [KSP.log](https://gist.githubusercontent.com/EnterTheNameHere/6902bb331e4e8952ce13e0f125351f38/raw/ed7fd886673ac7aeba4ed3b53bdfff596d1bcd64/KSP.log); [mods.ckan](https://gist.githubusercontent.com/EnterTheNameHere/6902bb331e4e8952ce13e0f125351f38/raw/ed7fd886673ac7aeba4ed3b53bdfff596d1bcd64/mods.ckan) )

**Comment by VirtualGaming1** [comment]
still an issue with version of 3.0.4
question is this your side or the ModuleManager?
