### ISSUE TITLE
Some parts don't deform well

### ISSUE THREAD

**Issue by inorton** [EnzoMeertens/KerbalKrashSystem#3]
Excellent mod btw :+1:  There are a handful of parts with moving sections that don't deform in an expected way when damaged (you probably know about them already).

* Wheels (uncarriage deform even with zero damage when doing a normal landing)
* Propellors (KAX/Firespitter propellers go very very wierd with damage)

So it sounds like some modules should be black listed from deformations.

**Comment by EnzoMeertens** [comment]
Fixed by excluding physicsless parts from deformation.

**Comment by inorton** [comment]
Thanks :)
