### ISSUE TITLE
KKS incompatibility with KIS 1.2.8

### ISSUE THREAD

**Issue by FalcoGer** [EnzoMeertens/KerbalKrashSystem#9]
KKS spams the log with

FileNotFoundException: Could not load file or assembly, 'KIS, version 1.2.7.6, culture=neutral, PublicKeyToken=null' or one of it's dependencies.

after update to latest KIS. It also creates a ghost Kerbal when entering a hatch, the ghost being stuck outside on the ladder, uncontrollable, which messes up the game when you try switching.

**Comment by Blu3wolf** [comment]
I wish Id found this issue say a day or two ago... just been through my install hunting down which mod caused this!

**Comment by EnzoMeertens** [comment]
Does this still happen in the latest version of KKS?

**Comment by Blu3wolf** [comment]
I have this issue with KIS 1.2.9 and KKS 0.3 (according to the version.txt file in the folder anyway).
